/*
 * dkPlus.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.DkCloudDataModelPermissionCRMPermissionModel;
import io.swagger.client.model.DkCloudDataModelPermissionCustomerPermissionModel;
import io.swagger.client.model.DkCloudDataModelPermissionGeneralLedgerPermissionModel;
import io.swagger.client.model.DkCloudDataModelPermissionGeneralPermissionModel;
import io.swagger.client.model.DkCloudDataModelPermissionMemberPermissionModel;
import io.swagger.client.model.DkCloudDataModelPermissionProductPermissionModel;
import io.swagger.client.model.DkCloudDataModelPermissionProjectPermissionModel;
import io.swagger.client.model.DkCloudDataModelPermissionPurchaseOrdertPermissionModel;
import io.swagger.client.model.DkCloudDataModelPermissionSalesPermissionModel;
import io.swagger.client.model.DkCloudDataModelPermissionVendorPermissionModel;
import java.io.IOException;

/**
 * DkCloudDataModelPermissionModulePermission
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-11-12T12:57:09.866Z")



public class DkCloudDataModelPermissionModulePermission {
  @SerializedName("GeneralLedgerPermission")
  private DkCloudDataModelPermissionGeneralLedgerPermissionModel generalLedgerPermission = null;

  @SerializedName("VendorPermission")
  private DkCloudDataModelPermissionVendorPermissionModel vendorPermission = null;

  @SerializedName("CustomerPermission")
  private DkCloudDataModelPermissionCustomerPermissionModel customerPermission = null;

  @SerializedName("ProductPermission")
  private DkCloudDataModelPermissionProductPermissionModel productPermission = null;

  @SerializedName("SalesPermission")
  private DkCloudDataModelPermissionSalesPermissionModel salesPermission = null;

  @SerializedName("MemberPermission")
  private DkCloudDataModelPermissionMemberPermissionModel memberPermission = null;

  @SerializedName("ProjectPermission")
  private DkCloudDataModelPermissionProjectPermissionModel projectPermission = null;

  @SerializedName("PurchaseOrderPermission")
  private DkCloudDataModelPermissionPurchaseOrdertPermissionModel purchaseOrderPermission = null;

  @SerializedName("CRMPermission")
  private DkCloudDataModelPermissionCRMPermissionModel crMPermission = null;

  @SerializedName("GeneralPermission")
  private DkCloudDataModelPermissionGeneralPermissionModel generalPermission = null;

  public DkCloudDataModelPermissionModulePermission generalLedgerPermission(DkCloudDataModelPermissionGeneralLedgerPermissionModel generalLedgerPermission) {
    this.generalLedgerPermission = generalLedgerPermission;
    return this;
  }

   /**
   * Get generalLedgerPermission
   * @return generalLedgerPermission
  **/
  @ApiModelProperty(value = "")
  public DkCloudDataModelPermissionGeneralLedgerPermissionModel getGeneralLedgerPermission() {
    return generalLedgerPermission;
  }

  public void setGeneralLedgerPermission(DkCloudDataModelPermissionGeneralLedgerPermissionModel generalLedgerPermission) {
    this.generalLedgerPermission = generalLedgerPermission;
  }

  public DkCloudDataModelPermissionModulePermission vendorPermission(DkCloudDataModelPermissionVendorPermissionModel vendorPermission) {
    this.vendorPermission = vendorPermission;
    return this;
  }

   /**
   * Get vendorPermission
   * @return vendorPermission
  **/
  @ApiModelProperty(value = "")
  public DkCloudDataModelPermissionVendorPermissionModel getVendorPermission() {
    return vendorPermission;
  }

  public void setVendorPermission(DkCloudDataModelPermissionVendorPermissionModel vendorPermission) {
    this.vendorPermission = vendorPermission;
  }

  public DkCloudDataModelPermissionModulePermission customerPermission(DkCloudDataModelPermissionCustomerPermissionModel customerPermission) {
    this.customerPermission = customerPermission;
    return this;
  }

   /**
   * Get customerPermission
   * @return customerPermission
  **/
  @ApiModelProperty(value = "")
  public DkCloudDataModelPermissionCustomerPermissionModel getCustomerPermission() {
    return customerPermission;
  }

  public void setCustomerPermission(DkCloudDataModelPermissionCustomerPermissionModel customerPermission) {
    this.customerPermission = customerPermission;
  }

  public DkCloudDataModelPermissionModulePermission productPermission(DkCloudDataModelPermissionProductPermissionModel productPermission) {
    this.productPermission = productPermission;
    return this;
  }

   /**
   * Get productPermission
   * @return productPermission
  **/
  @ApiModelProperty(value = "")
  public DkCloudDataModelPermissionProductPermissionModel getProductPermission() {
    return productPermission;
  }

  public void setProductPermission(DkCloudDataModelPermissionProductPermissionModel productPermission) {
    this.productPermission = productPermission;
  }

  public DkCloudDataModelPermissionModulePermission salesPermission(DkCloudDataModelPermissionSalesPermissionModel salesPermission) {
    this.salesPermission = salesPermission;
    return this;
  }

   /**
   * Get salesPermission
   * @return salesPermission
  **/
  @ApiModelProperty(value = "")
  public DkCloudDataModelPermissionSalesPermissionModel getSalesPermission() {
    return salesPermission;
  }

  public void setSalesPermission(DkCloudDataModelPermissionSalesPermissionModel salesPermission) {
    this.salesPermission = salesPermission;
  }

  public DkCloudDataModelPermissionModulePermission memberPermission(DkCloudDataModelPermissionMemberPermissionModel memberPermission) {
    this.memberPermission = memberPermission;
    return this;
  }

   /**
   * Get memberPermission
   * @return memberPermission
  **/
  @ApiModelProperty(value = "")
  public DkCloudDataModelPermissionMemberPermissionModel getMemberPermission() {
    return memberPermission;
  }

  public void setMemberPermission(DkCloudDataModelPermissionMemberPermissionModel memberPermission) {
    this.memberPermission = memberPermission;
  }

  public DkCloudDataModelPermissionModulePermission projectPermission(DkCloudDataModelPermissionProjectPermissionModel projectPermission) {
    this.projectPermission = projectPermission;
    return this;
  }

   /**
   * Get projectPermission
   * @return projectPermission
  **/
  @ApiModelProperty(value = "")
  public DkCloudDataModelPermissionProjectPermissionModel getProjectPermission() {
    return projectPermission;
  }

  public void setProjectPermission(DkCloudDataModelPermissionProjectPermissionModel projectPermission) {
    this.projectPermission = projectPermission;
  }

  public DkCloudDataModelPermissionModulePermission purchaseOrderPermission(DkCloudDataModelPermissionPurchaseOrdertPermissionModel purchaseOrderPermission) {
    this.purchaseOrderPermission = purchaseOrderPermission;
    return this;
  }

   /**
   * Get purchaseOrderPermission
   * @return purchaseOrderPermission
  **/
  @ApiModelProperty(value = "")
  public DkCloudDataModelPermissionPurchaseOrdertPermissionModel getPurchaseOrderPermission() {
    return purchaseOrderPermission;
  }

  public void setPurchaseOrderPermission(DkCloudDataModelPermissionPurchaseOrdertPermissionModel purchaseOrderPermission) {
    this.purchaseOrderPermission = purchaseOrderPermission;
  }

  public DkCloudDataModelPermissionModulePermission crMPermission(DkCloudDataModelPermissionCRMPermissionModel crMPermission) {
    this.crMPermission = crMPermission;
    return this;
  }

   /**
   * Get crMPermission
   * @return crMPermission
  **/
  @ApiModelProperty(value = "")
  public DkCloudDataModelPermissionCRMPermissionModel getCrMPermission() {
    return crMPermission;
  }

  public void setCrMPermission(DkCloudDataModelPermissionCRMPermissionModel crMPermission) {
    this.crMPermission = crMPermission;
  }

  public DkCloudDataModelPermissionModulePermission generalPermission(DkCloudDataModelPermissionGeneralPermissionModel generalPermission) {
    this.generalPermission = generalPermission;
    return this;
  }

   /**
   * Get generalPermission
   * @return generalPermission
  **/
  @ApiModelProperty(value = "")
  public DkCloudDataModelPermissionGeneralPermissionModel getGeneralPermission() {
    return generalPermission;
  }

  public void setGeneralPermission(DkCloudDataModelPermissionGeneralPermissionModel generalPermission) {
    this.generalPermission = generalPermission;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DkCloudDataModelPermissionModulePermission dkCloudDataModelPermissionModulePermission = (DkCloudDataModelPermissionModulePermission) o;
    return Objects.equals(this.generalLedgerPermission, dkCloudDataModelPermissionModulePermission.generalLedgerPermission) &&
        Objects.equals(this.vendorPermission, dkCloudDataModelPermissionModulePermission.vendorPermission) &&
        Objects.equals(this.customerPermission, dkCloudDataModelPermissionModulePermission.customerPermission) &&
        Objects.equals(this.productPermission, dkCloudDataModelPermissionModulePermission.productPermission) &&
        Objects.equals(this.salesPermission, dkCloudDataModelPermissionModulePermission.salesPermission) &&
        Objects.equals(this.memberPermission, dkCloudDataModelPermissionModulePermission.memberPermission) &&
        Objects.equals(this.projectPermission, dkCloudDataModelPermissionModulePermission.projectPermission) &&
        Objects.equals(this.purchaseOrderPermission, dkCloudDataModelPermissionModulePermission.purchaseOrderPermission) &&
        Objects.equals(this.crMPermission, dkCloudDataModelPermissionModulePermission.crMPermission) &&
        Objects.equals(this.generalPermission, dkCloudDataModelPermissionModulePermission.generalPermission);
  }

  @Override
  public int hashCode() {
    return Objects.hash(generalLedgerPermission, vendorPermission, customerPermission, productPermission, salesPermission, memberPermission, projectPermission, purchaseOrderPermission, crMPermission, generalPermission);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DkCloudDataModelPermissionModulePermission {\n");
    
    sb.append("    generalLedgerPermission: ").append(toIndentedString(generalLedgerPermission)).append("\n");
    sb.append("    vendorPermission: ").append(toIndentedString(vendorPermission)).append("\n");
    sb.append("    customerPermission: ").append(toIndentedString(customerPermission)).append("\n");
    sb.append("    productPermission: ").append(toIndentedString(productPermission)).append("\n");
    sb.append("    salesPermission: ").append(toIndentedString(salesPermission)).append("\n");
    sb.append("    memberPermission: ").append(toIndentedString(memberPermission)).append("\n");
    sb.append("    projectPermission: ").append(toIndentedString(projectPermission)).append("\n");
    sb.append("    purchaseOrderPermission: ").append(toIndentedString(purchaseOrderPermission)).append("\n");
    sb.append("    crMPermission: ").append(toIndentedString(crMPermission)).append("\n");
    sb.append("    generalPermission: ").append(toIndentedString(generalPermission)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

