/*
 * dkPlus.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.DkCloudDataModelMembersFieldRequirement;
import java.io.IOException;

/**
 * DkCloudDataModelMembersGrantFieldRequirements
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-11-12T12:57:09.866Z")



public class DkCloudDataModelMembersGrantFieldRequirements {
  @SerializedName("Amount")
  private DkCloudDataModelMembersFieldRequirement amount = null;

  @SerializedName("Comment")
  private DkCloudDataModelMembersFieldRequirement comment = null;

  @SerializedName("Description")
  private DkCloudDataModelMembersFieldRequirement description = null;

  @SerializedName("GrantCount")
  private DkCloudDataModelMembersFieldRequirement grantCount = null;

  @SerializedName("Location")
  private DkCloudDataModelMembersFieldRequirement location = null;

  @SerializedName("Organizer")
  private DkCloudDataModelMembersFieldRequirement organizer = null;

  @SerializedName("Period")
  private DkCloudDataModelMembersFieldRequirement period = null;

  @SerializedName("PeriodToRequired")
  private Boolean periodToRequired = null;

  @SerializedName("Purpose")
  private DkCloudDataModelMembersFieldRequirement purpose = null;

  @SerializedName("Reference")
  private DkCloudDataModelMembersFieldRequirement reference = null;

  @SerializedName("Text1")
  private DkCloudDataModelMembersFieldRequirement text1 = null;

  @SerializedName("Text2")
  private DkCloudDataModelMembersFieldRequirement text2 = null;

  @SerializedName("UnitCount")
  private DkCloudDataModelMembersFieldRequirement unitCount = null;

  @SerializedName("FundCodeRequired")
  private Boolean fundCodeRequired = null;

  @SerializedName("GrantRequired")
  private Boolean grantRequired = null;

  @SerializedName("JobRatioRequired")
  private Boolean jobRatioRequired = null;

  @SerializedName("JobTitleRequired")
  private Boolean jobTitleRequired = null;

  @SerializedName("MemberRequired")
  private Boolean memberRequired = null;

  @SerializedName("WorkplaceRequired")
  private Boolean workplaceRequired = null;

  @SerializedName("WPHistoryJobRatioRequired")
  private Boolean wpHistoryJobRatioRequired = null;

  @SerializedName("WPHistoryRequired")
  private Boolean wpHistoryRequired = null;

  public DkCloudDataModelMembersGrantFieldRequirements amount(DkCloudDataModelMembersFieldRequirement amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @ApiModelProperty(value = "")
  public DkCloudDataModelMembersFieldRequirement getAmount() {
    return amount;
  }

  public void setAmount(DkCloudDataModelMembersFieldRequirement amount) {
    this.amount = amount;
  }

  public DkCloudDataModelMembersGrantFieldRequirements comment(DkCloudDataModelMembersFieldRequirement comment) {
    this.comment = comment;
    return this;
  }

   /**
   * Get comment
   * @return comment
  **/
  @ApiModelProperty(value = "")
  public DkCloudDataModelMembersFieldRequirement getComment() {
    return comment;
  }

  public void setComment(DkCloudDataModelMembersFieldRequirement comment) {
    this.comment = comment;
  }

  public DkCloudDataModelMembersGrantFieldRequirements description(DkCloudDataModelMembersFieldRequirement description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public DkCloudDataModelMembersFieldRequirement getDescription() {
    return description;
  }

  public void setDescription(DkCloudDataModelMembersFieldRequirement description) {
    this.description = description;
  }

  public DkCloudDataModelMembersGrantFieldRequirements grantCount(DkCloudDataModelMembersFieldRequirement grantCount) {
    this.grantCount = grantCount;
    return this;
  }

   /**
   * Get grantCount
   * @return grantCount
  **/
  @ApiModelProperty(value = "")
  public DkCloudDataModelMembersFieldRequirement getGrantCount() {
    return grantCount;
  }

  public void setGrantCount(DkCloudDataModelMembersFieldRequirement grantCount) {
    this.grantCount = grantCount;
  }

  public DkCloudDataModelMembersGrantFieldRequirements location(DkCloudDataModelMembersFieldRequirement location) {
    this.location = location;
    return this;
  }

   /**
   * Get location
   * @return location
  **/
  @ApiModelProperty(value = "")
  public DkCloudDataModelMembersFieldRequirement getLocation() {
    return location;
  }

  public void setLocation(DkCloudDataModelMembersFieldRequirement location) {
    this.location = location;
  }

  public DkCloudDataModelMembersGrantFieldRequirements organizer(DkCloudDataModelMembersFieldRequirement organizer) {
    this.organizer = organizer;
    return this;
  }

   /**
   * Get organizer
   * @return organizer
  **/
  @ApiModelProperty(value = "")
  public DkCloudDataModelMembersFieldRequirement getOrganizer() {
    return organizer;
  }

  public void setOrganizer(DkCloudDataModelMembersFieldRequirement organizer) {
    this.organizer = organizer;
  }

  public DkCloudDataModelMembersGrantFieldRequirements period(DkCloudDataModelMembersFieldRequirement period) {
    this.period = period;
    return this;
  }

   /**
   * Get period
   * @return period
  **/
  @ApiModelProperty(value = "")
  public DkCloudDataModelMembersFieldRequirement getPeriod() {
    return period;
  }

  public void setPeriod(DkCloudDataModelMembersFieldRequirement period) {
    this.period = period;
  }

   /**
   * Get periodToRequired
   * @return periodToRequired
  **/
  @ApiModelProperty(value = "")
  public Boolean isPeriodToRequired() {
    return periodToRequired;
  }

  public DkCloudDataModelMembersGrantFieldRequirements purpose(DkCloudDataModelMembersFieldRequirement purpose) {
    this.purpose = purpose;
    return this;
  }

   /**
   * Get purpose
   * @return purpose
  **/
  @ApiModelProperty(value = "")
  public DkCloudDataModelMembersFieldRequirement getPurpose() {
    return purpose;
  }

  public void setPurpose(DkCloudDataModelMembersFieldRequirement purpose) {
    this.purpose = purpose;
  }

  public DkCloudDataModelMembersGrantFieldRequirements reference(DkCloudDataModelMembersFieldRequirement reference) {
    this.reference = reference;
    return this;
  }

   /**
   * Get reference
   * @return reference
  **/
  @ApiModelProperty(value = "")
  public DkCloudDataModelMembersFieldRequirement getReference() {
    return reference;
  }

  public void setReference(DkCloudDataModelMembersFieldRequirement reference) {
    this.reference = reference;
  }

  public DkCloudDataModelMembersGrantFieldRequirements text1(DkCloudDataModelMembersFieldRequirement text1) {
    this.text1 = text1;
    return this;
  }

   /**
   * Get text1
   * @return text1
  **/
  @ApiModelProperty(value = "")
  public DkCloudDataModelMembersFieldRequirement getText1() {
    return text1;
  }

  public void setText1(DkCloudDataModelMembersFieldRequirement text1) {
    this.text1 = text1;
  }

  public DkCloudDataModelMembersGrantFieldRequirements text2(DkCloudDataModelMembersFieldRequirement text2) {
    this.text2 = text2;
    return this;
  }

   /**
   * Get text2
   * @return text2
  **/
  @ApiModelProperty(value = "")
  public DkCloudDataModelMembersFieldRequirement getText2() {
    return text2;
  }

  public void setText2(DkCloudDataModelMembersFieldRequirement text2) {
    this.text2 = text2;
  }

  public DkCloudDataModelMembersGrantFieldRequirements unitCount(DkCloudDataModelMembersFieldRequirement unitCount) {
    this.unitCount = unitCount;
    return this;
  }

   /**
   * Get unitCount
   * @return unitCount
  **/
  @ApiModelProperty(value = "")
  public DkCloudDataModelMembersFieldRequirement getUnitCount() {
    return unitCount;
  }

  public void setUnitCount(DkCloudDataModelMembersFieldRequirement unitCount) {
    this.unitCount = unitCount;
  }

   /**
   * Get fundCodeRequired
   * @return fundCodeRequired
  **/
  @ApiModelProperty(value = "")
  public Boolean isFundCodeRequired() {
    return fundCodeRequired;
  }

   /**
   * Get grantRequired
   * @return grantRequired
  **/
  @ApiModelProperty(value = "")
  public Boolean isGrantRequired() {
    return grantRequired;
  }

   /**
   * Get jobRatioRequired
   * @return jobRatioRequired
  **/
  @ApiModelProperty(value = "")
  public Boolean isJobRatioRequired() {
    return jobRatioRequired;
  }

   /**
   * Get jobTitleRequired
   * @return jobTitleRequired
  **/
  @ApiModelProperty(value = "")
  public Boolean isJobTitleRequired() {
    return jobTitleRequired;
  }

   /**
   * Get memberRequired
   * @return memberRequired
  **/
  @ApiModelProperty(value = "")
  public Boolean isMemberRequired() {
    return memberRequired;
  }

   /**
   * Get workplaceRequired
   * @return workplaceRequired
  **/
  @ApiModelProperty(value = "")
  public Boolean isWorkplaceRequired() {
    return workplaceRequired;
  }

   /**
   * Get wpHistoryJobRatioRequired
   * @return wpHistoryJobRatioRequired
  **/
  @ApiModelProperty(value = "")
  public Boolean isWpHistoryJobRatioRequired() {
    return wpHistoryJobRatioRequired;
  }

   /**
   * Get wpHistoryRequired
   * @return wpHistoryRequired
  **/
  @ApiModelProperty(value = "")
  public Boolean isWpHistoryRequired() {
    return wpHistoryRequired;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DkCloudDataModelMembersGrantFieldRequirements dkCloudDataModelMembersGrantFieldRequirements = (DkCloudDataModelMembersGrantFieldRequirements) o;
    return Objects.equals(this.amount, dkCloudDataModelMembersGrantFieldRequirements.amount) &&
        Objects.equals(this.comment, dkCloudDataModelMembersGrantFieldRequirements.comment) &&
        Objects.equals(this.description, dkCloudDataModelMembersGrantFieldRequirements.description) &&
        Objects.equals(this.grantCount, dkCloudDataModelMembersGrantFieldRequirements.grantCount) &&
        Objects.equals(this.location, dkCloudDataModelMembersGrantFieldRequirements.location) &&
        Objects.equals(this.organizer, dkCloudDataModelMembersGrantFieldRequirements.organizer) &&
        Objects.equals(this.period, dkCloudDataModelMembersGrantFieldRequirements.period) &&
        Objects.equals(this.periodToRequired, dkCloudDataModelMembersGrantFieldRequirements.periodToRequired) &&
        Objects.equals(this.purpose, dkCloudDataModelMembersGrantFieldRequirements.purpose) &&
        Objects.equals(this.reference, dkCloudDataModelMembersGrantFieldRequirements.reference) &&
        Objects.equals(this.text1, dkCloudDataModelMembersGrantFieldRequirements.text1) &&
        Objects.equals(this.text2, dkCloudDataModelMembersGrantFieldRequirements.text2) &&
        Objects.equals(this.unitCount, dkCloudDataModelMembersGrantFieldRequirements.unitCount) &&
        Objects.equals(this.fundCodeRequired, dkCloudDataModelMembersGrantFieldRequirements.fundCodeRequired) &&
        Objects.equals(this.grantRequired, dkCloudDataModelMembersGrantFieldRequirements.grantRequired) &&
        Objects.equals(this.jobRatioRequired, dkCloudDataModelMembersGrantFieldRequirements.jobRatioRequired) &&
        Objects.equals(this.jobTitleRequired, dkCloudDataModelMembersGrantFieldRequirements.jobTitleRequired) &&
        Objects.equals(this.memberRequired, dkCloudDataModelMembersGrantFieldRequirements.memberRequired) &&
        Objects.equals(this.workplaceRequired, dkCloudDataModelMembersGrantFieldRequirements.workplaceRequired) &&
        Objects.equals(this.wpHistoryJobRatioRequired, dkCloudDataModelMembersGrantFieldRequirements.wpHistoryJobRatioRequired) &&
        Objects.equals(this.wpHistoryRequired, dkCloudDataModelMembersGrantFieldRequirements.wpHistoryRequired);
  }

  @Override
  public int hashCode() {
    return Objects.hash(amount, comment, description, grantCount, location, organizer, period, periodToRequired, purpose, reference, text1, text2, unitCount, fundCodeRequired, grantRequired, jobRatioRequired, jobTitleRequired, memberRequired, workplaceRequired, wpHistoryJobRatioRequired, wpHistoryRequired);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DkCloudDataModelMembersGrantFieldRequirements {\n");
    
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    grantCount: ").append(toIndentedString(grantCount)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    organizer: ").append(toIndentedString(organizer)).append("\n");
    sb.append("    period: ").append(toIndentedString(period)).append("\n");
    sb.append("    periodToRequired: ").append(toIndentedString(periodToRequired)).append("\n");
    sb.append("    purpose: ").append(toIndentedString(purpose)).append("\n");
    sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
    sb.append("    text1: ").append(toIndentedString(text1)).append("\n");
    sb.append("    text2: ").append(toIndentedString(text2)).append("\n");
    sb.append("    unitCount: ").append(toIndentedString(unitCount)).append("\n");
    sb.append("    fundCodeRequired: ").append(toIndentedString(fundCodeRequired)).append("\n");
    sb.append("    grantRequired: ").append(toIndentedString(grantRequired)).append("\n");
    sb.append("    jobRatioRequired: ").append(toIndentedString(jobRatioRequired)).append("\n");
    sb.append("    jobTitleRequired: ").append(toIndentedString(jobTitleRequired)).append("\n");
    sb.append("    memberRequired: ").append(toIndentedString(memberRequired)).append("\n");
    sb.append("    workplaceRequired: ").append(toIndentedString(workplaceRequired)).append("\n");
    sb.append("    wpHistoryJobRatioRequired: ").append(toIndentedString(wpHistoryJobRatioRequired)).append("\n");
    sb.append("    wpHistoryRequired: ").append(toIndentedString(wpHistoryRequired)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

