/*
 * dkPlus.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.DkCloudDataModelCustomersContactModel;
import io.swagger.client.model.DkCloudDataModelCustomersCustomerCondition;
import io.swagger.client.model.DkCloudDataModelCustomersCustomerMemoModel;
import io.swagger.client.model.DkCloudDataModelCustomersCustomerPropertyModel;
import io.swagger.client.model.DkCloudDataModelCustomersCustomerSendTo;
import io.swagger.client.model.DkCloudDataModelCustomersItemReciverModel;
import io.swagger.client.model.DkCloudDataModelGeneralAttachmentModel;
import io.swagger.client.model.DkCloudDataModelGeneralChangesModel;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;

/**
 * DkCloudDataModelCustomersCustomerModel
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-11-12T12:57:09.866Z")



public class DkCloudDataModelCustomersCustomerModel {
  @SerializedName("Number")
  private String number = null;

  @SerializedName("Deleted")
  private Boolean deleted = null;

  @SerializedName("Contacts")
  private List<DkCloudDataModelCustomersContactModel> contacts = null;

  @SerializedName("Recivers")
  private List<DkCloudDataModelCustomersItemReciverModel> recivers = null;

  @SerializedName("Memos")
  private List<DkCloudDataModelCustomersCustomerMemoModel> memos = null;

  @SerializedName("Properties")
  private List<DkCloudDataModelCustomersCustomerPropertyModel> properties = null;

  @SerializedName("Changes")
  private List<DkCloudDataModelGeneralChangesModel> changes = null;

  @SerializedName("Attachments")
  private List<DkCloudDataModelGeneralAttachmentModel> attachments = null;

  @SerializedName("Conditions")
  private DkCloudDataModelCustomersCustomerCondition conditions = null;

  @SerializedName("SendTo")
  private DkCloudDataModelCustomersCustomerSendTo sendTo = null;

  @SerializedName("RecordID")
  private Long recordID = null;

  @SerializedName("Name")
  private String name = null;

  @SerializedName("Alias")
  private String alias = null;

  @SerializedName("Address1")
  private String address1 = null;

  @SerializedName("Address2")
  private String address2 = null;

  @SerializedName("Address3")
  private String address3 = null;

  @SerializedName("ZipCode")
  private String zipCode = null;

  @SerializedName("BalanceAmount")
  private Double balanceAmount = null;

  @SerializedName("Phone")
  private String phone = null;

  @SerializedName("PhoneLocal")
  private String phoneLocal = null;

  @SerializedName("PhoneMobile")
  private String phoneMobile = null;

  @SerializedName("PhoneFax")
  private String phoneFax = null;

  @SerializedName("CountryCode")
  private String countryCode = null;

  @SerializedName("OriginCountryCode")
  private String originCountryCode = null;

  @SerializedName("Email")
  private String email = null;

  @SerializedName("Password")
  private String password = null;

  @SerializedName("Group")
  private String group = null;

  @SerializedName("SalesPerson")
  private String salesPerson = null;

  @SerializedName("Discount")
  private Double discount = null;

  @SerializedName("UseItemRecivers")
  private Boolean useItemRecivers = null;

  @SerializedName("PaymentTerm")
  private String paymentTerm = null;

  @SerializedName("PaymentMode")
  private String paymentMode = null;

  @SerializedName("CurrencyCode")
  private String currencyCode = null;

  @SerializedName("NoVat")
  private Boolean noVat = null;

  @SerializedName("LedgerCode")
  private String ledgerCode = null;

  @SerializedName("Blocked")
  private Boolean blocked = null;

  /**
   * Gets or Sets gender
   */
  @JsonAdapter(GenderEnum.Adapter.class)
  public enum GenderEnum {
    MALE("Male"),
    
    FEMALE("Female"),
    
    GENDERCOMPANY("GenderCompany"),
    
    NOGENDER("NoGender"),
    
    NOTEXISTS("NotExists"),
    
    BOY("Boy"),
    
    GIRL("Girl");

    private String value;

    GenderEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static GenderEnum fromValue(String text) {
      for (GenderEnum b : GenderEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<GenderEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final GenderEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public GenderEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return GenderEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("Gender")
  private GenderEnum gender = null;

  @SerializedName("PriceGroup")
  private Integer priceGroup = null;

  @SerializedName("BillingFee")
  private Double billingFee = null;

  @SerializedName("Modified")
  private OffsetDateTime modified = null;

  public DkCloudDataModelCustomersCustomerModel number(String number) {
    this.number = number;
    return this;
  }

   /**
   * Get number
   * @return number
  **/
  @ApiModelProperty(required = true, value = "")
  public String getNumber() {
    return number;
  }

  public void setNumber(String number) {
    this.number = number;
  }

  public DkCloudDataModelCustomersCustomerModel deleted(Boolean deleted) {
    this.deleted = deleted;
    return this;
  }

   /**
   * Get deleted
   * @return deleted
  **/
  @ApiModelProperty(value = "")
  public Boolean isDeleted() {
    return deleted;
  }

  public void setDeleted(Boolean deleted) {
    this.deleted = deleted;
  }

  public DkCloudDataModelCustomersCustomerModel contacts(List<DkCloudDataModelCustomersContactModel> contacts) {
    this.contacts = contacts;
    return this;
  }

  public DkCloudDataModelCustomersCustomerModel addContactsItem(DkCloudDataModelCustomersContactModel contactsItem) {
    if (this.contacts == null) {
      this.contacts = new ArrayList<DkCloudDataModelCustomersContactModel>();
    }
    this.contacts.add(contactsItem);
    return this;
  }

   /**
   * Get contacts
   * @return contacts
  **/
  @ApiModelProperty(value = "")
  public List<DkCloudDataModelCustomersContactModel> getContacts() {
    return contacts;
  }

  public void setContacts(List<DkCloudDataModelCustomersContactModel> contacts) {
    this.contacts = contacts;
  }

  public DkCloudDataModelCustomersCustomerModel recivers(List<DkCloudDataModelCustomersItemReciverModel> recivers) {
    this.recivers = recivers;
    return this;
  }

  public DkCloudDataModelCustomersCustomerModel addReciversItem(DkCloudDataModelCustomersItemReciverModel reciversItem) {
    if (this.recivers == null) {
      this.recivers = new ArrayList<DkCloudDataModelCustomersItemReciverModel>();
    }
    this.recivers.add(reciversItem);
    return this;
  }

   /**
   * Get recivers
   * @return recivers
  **/
  @ApiModelProperty(value = "")
  public List<DkCloudDataModelCustomersItemReciverModel> getRecivers() {
    return recivers;
  }

  public void setRecivers(List<DkCloudDataModelCustomersItemReciverModel> recivers) {
    this.recivers = recivers;
  }

  public DkCloudDataModelCustomersCustomerModel memos(List<DkCloudDataModelCustomersCustomerMemoModel> memos) {
    this.memos = memos;
    return this;
  }

  public DkCloudDataModelCustomersCustomerModel addMemosItem(DkCloudDataModelCustomersCustomerMemoModel memosItem) {
    if (this.memos == null) {
      this.memos = new ArrayList<DkCloudDataModelCustomersCustomerMemoModel>();
    }
    this.memos.add(memosItem);
    return this;
  }

   /**
   * Get memos
   * @return memos
  **/
  @ApiModelProperty(value = "")
  public List<DkCloudDataModelCustomersCustomerMemoModel> getMemos() {
    return memos;
  }

  public void setMemos(List<DkCloudDataModelCustomersCustomerMemoModel> memos) {
    this.memos = memos;
  }

  public DkCloudDataModelCustomersCustomerModel properties(List<DkCloudDataModelCustomersCustomerPropertyModel> properties) {
    this.properties = properties;
    return this;
  }

  public DkCloudDataModelCustomersCustomerModel addPropertiesItem(DkCloudDataModelCustomersCustomerPropertyModel propertiesItem) {
    if (this.properties == null) {
      this.properties = new ArrayList<DkCloudDataModelCustomersCustomerPropertyModel>();
    }
    this.properties.add(propertiesItem);
    return this;
  }

   /**
   * Get properties
   * @return properties
  **/
  @ApiModelProperty(value = "")
  public List<DkCloudDataModelCustomersCustomerPropertyModel> getProperties() {
    return properties;
  }

  public void setProperties(List<DkCloudDataModelCustomersCustomerPropertyModel> properties) {
    this.properties = properties;
  }

  public DkCloudDataModelCustomersCustomerModel changes(List<DkCloudDataModelGeneralChangesModel> changes) {
    this.changes = changes;
    return this;
  }

  public DkCloudDataModelCustomersCustomerModel addChangesItem(DkCloudDataModelGeneralChangesModel changesItem) {
    if (this.changes == null) {
      this.changes = new ArrayList<DkCloudDataModelGeneralChangesModel>();
    }
    this.changes.add(changesItem);
    return this;
  }

   /**
   * Get changes
   * @return changes
  **/
  @ApiModelProperty(value = "")
  public List<DkCloudDataModelGeneralChangesModel> getChanges() {
    return changes;
  }

  public void setChanges(List<DkCloudDataModelGeneralChangesModel> changes) {
    this.changes = changes;
  }

  public DkCloudDataModelCustomersCustomerModel attachments(List<DkCloudDataModelGeneralAttachmentModel> attachments) {
    this.attachments = attachments;
    return this;
  }

  public DkCloudDataModelCustomersCustomerModel addAttachmentsItem(DkCloudDataModelGeneralAttachmentModel attachmentsItem) {
    if (this.attachments == null) {
      this.attachments = new ArrayList<DkCloudDataModelGeneralAttachmentModel>();
    }
    this.attachments.add(attachmentsItem);
    return this;
  }

   /**
   * Get attachments
   * @return attachments
  **/
  @ApiModelProperty(value = "")
  public List<DkCloudDataModelGeneralAttachmentModel> getAttachments() {
    return attachments;
  }

  public void setAttachments(List<DkCloudDataModelGeneralAttachmentModel> attachments) {
    this.attachments = attachments;
  }

  public DkCloudDataModelCustomersCustomerModel conditions(DkCloudDataModelCustomersCustomerCondition conditions) {
    this.conditions = conditions;
    return this;
  }

   /**
   * Get conditions
   * @return conditions
  **/
  @ApiModelProperty(value = "")
  public DkCloudDataModelCustomersCustomerCondition getConditions() {
    return conditions;
  }

  public void setConditions(DkCloudDataModelCustomersCustomerCondition conditions) {
    this.conditions = conditions;
  }

  public DkCloudDataModelCustomersCustomerModel sendTo(DkCloudDataModelCustomersCustomerSendTo sendTo) {
    this.sendTo = sendTo;
    return this;
  }

   /**
   * Get sendTo
   * @return sendTo
  **/
  @ApiModelProperty(value = "")
  public DkCloudDataModelCustomersCustomerSendTo getSendTo() {
    return sendTo;
  }

  public void setSendTo(DkCloudDataModelCustomersCustomerSendTo sendTo) {
    this.sendTo = sendTo;
  }

  public DkCloudDataModelCustomersCustomerModel recordID(Long recordID) {
    this.recordID = recordID;
    return this;
  }

   /**
   * Get recordID
   * @return recordID
  **/
  @ApiModelProperty(value = "")
  public Long getRecordID() {
    return recordID;
  }

  public void setRecordID(Long recordID) {
    this.recordID = recordID;
  }

  public DkCloudDataModelCustomersCustomerModel name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public DkCloudDataModelCustomersCustomerModel alias(String alias) {
    this.alias = alias;
    return this;
  }

   /**
   * Get alias
   * @return alias
  **/
  @ApiModelProperty(value = "")
  public String getAlias() {
    return alias;
  }

  public void setAlias(String alias) {
    this.alias = alias;
  }

  public DkCloudDataModelCustomersCustomerModel address1(String address1) {
    this.address1 = address1;
    return this;
  }

   /**
   * Get address1
   * @return address1
  **/
  @ApiModelProperty(value = "")
  public String getAddress1() {
    return address1;
  }

  public void setAddress1(String address1) {
    this.address1 = address1;
  }

  public DkCloudDataModelCustomersCustomerModel address2(String address2) {
    this.address2 = address2;
    return this;
  }

   /**
   * Get address2
   * @return address2
  **/
  @ApiModelProperty(value = "")
  public String getAddress2() {
    return address2;
  }

  public void setAddress2(String address2) {
    this.address2 = address2;
  }

  public DkCloudDataModelCustomersCustomerModel address3(String address3) {
    this.address3 = address3;
    return this;
  }

   /**
   * Get address3
   * @return address3
  **/
  @ApiModelProperty(value = "")
  public String getAddress3() {
    return address3;
  }

  public void setAddress3(String address3) {
    this.address3 = address3;
  }

  public DkCloudDataModelCustomersCustomerModel zipCode(String zipCode) {
    this.zipCode = zipCode;
    return this;
  }

   /**
   * Get zipCode
   * @return zipCode
  **/
  @ApiModelProperty(value = "")
  public String getZipCode() {
    return zipCode;
  }

  public void setZipCode(String zipCode) {
    this.zipCode = zipCode;
  }

  public DkCloudDataModelCustomersCustomerModel balanceAmount(Double balanceAmount) {
    this.balanceAmount = balanceAmount;
    return this;
  }

   /**
   * Get balanceAmount
   * @return balanceAmount
  **/
  @ApiModelProperty(value = "")
  public Double getBalanceAmount() {
    return balanceAmount;
  }

  public void setBalanceAmount(Double balanceAmount) {
    this.balanceAmount = balanceAmount;
  }

  public DkCloudDataModelCustomersCustomerModel phone(String phone) {
    this.phone = phone;
    return this;
  }

   /**
   * Get phone
   * @return phone
  **/
  @ApiModelProperty(value = "")
  public String getPhone() {
    return phone;
  }

  public void setPhone(String phone) {
    this.phone = phone;
  }

  public DkCloudDataModelCustomersCustomerModel phoneLocal(String phoneLocal) {
    this.phoneLocal = phoneLocal;
    return this;
  }

   /**
   * Get phoneLocal
   * @return phoneLocal
  **/
  @ApiModelProperty(value = "")
  public String getPhoneLocal() {
    return phoneLocal;
  }

  public void setPhoneLocal(String phoneLocal) {
    this.phoneLocal = phoneLocal;
  }

  public DkCloudDataModelCustomersCustomerModel phoneMobile(String phoneMobile) {
    this.phoneMobile = phoneMobile;
    return this;
  }

   /**
   * Get phoneMobile
   * @return phoneMobile
  **/
  @ApiModelProperty(value = "")
  public String getPhoneMobile() {
    return phoneMobile;
  }

  public void setPhoneMobile(String phoneMobile) {
    this.phoneMobile = phoneMobile;
  }

  public DkCloudDataModelCustomersCustomerModel phoneFax(String phoneFax) {
    this.phoneFax = phoneFax;
    return this;
  }

   /**
   * Get phoneFax
   * @return phoneFax
  **/
  @ApiModelProperty(value = "")
  public String getPhoneFax() {
    return phoneFax;
  }

  public void setPhoneFax(String phoneFax) {
    this.phoneFax = phoneFax;
  }

  public DkCloudDataModelCustomersCustomerModel countryCode(String countryCode) {
    this.countryCode = countryCode;
    return this;
  }

   /**
   * Get countryCode
   * @return countryCode
  **/
  @ApiModelProperty(value = "")
  public String getCountryCode() {
    return countryCode;
  }

  public void setCountryCode(String countryCode) {
    this.countryCode = countryCode;
  }

  public DkCloudDataModelCustomersCustomerModel originCountryCode(String originCountryCode) {
    this.originCountryCode = originCountryCode;
    return this;
  }

   /**
   * Get originCountryCode
   * @return originCountryCode
  **/
  @ApiModelProperty(value = "")
  public String getOriginCountryCode() {
    return originCountryCode;
  }

  public void setOriginCountryCode(String originCountryCode) {
    this.originCountryCode = originCountryCode;
  }

  public DkCloudDataModelCustomersCustomerModel email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @ApiModelProperty(value = "")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public DkCloudDataModelCustomersCustomerModel password(String password) {
    this.password = password;
    return this;
  }

   /**
   * Get password
   * @return password
  **/
  @ApiModelProperty(value = "")
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public DkCloudDataModelCustomersCustomerModel group(String group) {
    this.group = group;
    return this;
  }

   /**
   * Get group
   * @return group
  **/
  @ApiModelProperty(value = "")
  public String getGroup() {
    return group;
  }

  public void setGroup(String group) {
    this.group = group;
  }

  public DkCloudDataModelCustomersCustomerModel salesPerson(String salesPerson) {
    this.salesPerson = salesPerson;
    return this;
  }

   /**
   * Get salesPerson
   * @return salesPerson
  **/
  @ApiModelProperty(value = "")
  public String getSalesPerson() {
    return salesPerson;
  }

  public void setSalesPerson(String salesPerson) {
    this.salesPerson = salesPerson;
  }

  public DkCloudDataModelCustomersCustomerModel discount(Double discount) {
    this.discount = discount;
    return this;
  }

   /**
   * Get discount
   * @return discount
  **/
  @ApiModelProperty(value = "")
  public Double getDiscount() {
    return discount;
  }

  public void setDiscount(Double discount) {
    this.discount = discount;
  }

  public DkCloudDataModelCustomersCustomerModel useItemRecivers(Boolean useItemRecivers) {
    this.useItemRecivers = useItemRecivers;
    return this;
  }

   /**
   * Get useItemRecivers
   * @return useItemRecivers
  **/
  @ApiModelProperty(value = "")
  public Boolean isUseItemRecivers() {
    return useItemRecivers;
  }

  public void setUseItemRecivers(Boolean useItemRecivers) {
    this.useItemRecivers = useItemRecivers;
  }

  public DkCloudDataModelCustomersCustomerModel paymentTerm(String paymentTerm) {
    this.paymentTerm = paymentTerm;
    return this;
  }

   /**
   * Get paymentTerm
   * @return paymentTerm
  **/
  @ApiModelProperty(value = "")
  public String getPaymentTerm() {
    return paymentTerm;
  }

  public void setPaymentTerm(String paymentTerm) {
    this.paymentTerm = paymentTerm;
  }

  public DkCloudDataModelCustomersCustomerModel paymentMode(String paymentMode) {
    this.paymentMode = paymentMode;
    return this;
  }

   /**
   * Get paymentMode
   * @return paymentMode
  **/
  @ApiModelProperty(value = "")
  public String getPaymentMode() {
    return paymentMode;
  }

  public void setPaymentMode(String paymentMode) {
    this.paymentMode = paymentMode;
  }

  public DkCloudDataModelCustomersCustomerModel currencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
    return this;
  }

   /**
   * Get currencyCode
   * @return currencyCode
  **/
  @ApiModelProperty(value = "")
  public String getCurrencyCode() {
    return currencyCode;
  }

  public void setCurrencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
  }

  public DkCloudDataModelCustomersCustomerModel noVat(Boolean noVat) {
    this.noVat = noVat;
    return this;
  }

   /**
   * Get noVat
   * @return noVat
  **/
  @ApiModelProperty(value = "")
  public Boolean isNoVat() {
    return noVat;
  }

  public void setNoVat(Boolean noVat) {
    this.noVat = noVat;
  }

  public DkCloudDataModelCustomersCustomerModel ledgerCode(String ledgerCode) {
    this.ledgerCode = ledgerCode;
    return this;
  }

   /**
   * Get ledgerCode
   * @return ledgerCode
  **/
  @ApiModelProperty(value = "")
  public String getLedgerCode() {
    return ledgerCode;
  }

  public void setLedgerCode(String ledgerCode) {
    this.ledgerCode = ledgerCode;
  }

  public DkCloudDataModelCustomersCustomerModel blocked(Boolean blocked) {
    this.blocked = blocked;
    return this;
  }

   /**
   * Get blocked
   * @return blocked
  **/
  @ApiModelProperty(value = "")
  public Boolean isBlocked() {
    return blocked;
  }

  public void setBlocked(Boolean blocked) {
    this.blocked = blocked;
  }

  public DkCloudDataModelCustomersCustomerModel gender(GenderEnum gender) {
    this.gender = gender;
    return this;
  }

   /**
   * Get gender
   * @return gender
  **/
  @ApiModelProperty(value = "")
  public GenderEnum getGender() {
    return gender;
  }

  public void setGender(GenderEnum gender) {
    this.gender = gender;
  }

  public DkCloudDataModelCustomersCustomerModel priceGroup(Integer priceGroup) {
    this.priceGroup = priceGroup;
    return this;
  }

   /**
   * Get priceGroup
   * @return priceGroup
  **/
  @ApiModelProperty(value = "")
  public Integer getPriceGroup() {
    return priceGroup;
  }

  public void setPriceGroup(Integer priceGroup) {
    this.priceGroup = priceGroup;
  }

  public DkCloudDataModelCustomersCustomerModel billingFee(Double billingFee) {
    this.billingFee = billingFee;
    return this;
  }

   /**
   * Get billingFee
   * @return billingFee
  **/
  @ApiModelProperty(value = "")
  public Double getBillingFee() {
    return billingFee;
  }

  public void setBillingFee(Double billingFee) {
    this.billingFee = billingFee;
  }

  public DkCloudDataModelCustomersCustomerModel modified(OffsetDateTime modified) {
    this.modified = modified;
    return this;
  }

   /**
   * Get modified
   * @return modified
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getModified() {
    return modified;
  }

  public void setModified(OffsetDateTime modified) {
    this.modified = modified;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DkCloudDataModelCustomersCustomerModel dkCloudDataModelCustomersCustomerModel = (DkCloudDataModelCustomersCustomerModel) o;
    return Objects.equals(this.number, dkCloudDataModelCustomersCustomerModel.number) &&
        Objects.equals(this.deleted, dkCloudDataModelCustomersCustomerModel.deleted) &&
        Objects.equals(this.contacts, dkCloudDataModelCustomersCustomerModel.contacts) &&
        Objects.equals(this.recivers, dkCloudDataModelCustomersCustomerModel.recivers) &&
        Objects.equals(this.memos, dkCloudDataModelCustomersCustomerModel.memos) &&
        Objects.equals(this.properties, dkCloudDataModelCustomersCustomerModel.properties) &&
        Objects.equals(this.changes, dkCloudDataModelCustomersCustomerModel.changes) &&
        Objects.equals(this.attachments, dkCloudDataModelCustomersCustomerModel.attachments) &&
        Objects.equals(this.conditions, dkCloudDataModelCustomersCustomerModel.conditions) &&
        Objects.equals(this.sendTo, dkCloudDataModelCustomersCustomerModel.sendTo) &&
        Objects.equals(this.recordID, dkCloudDataModelCustomersCustomerModel.recordID) &&
        Objects.equals(this.name, dkCloudDataModelCustomersCustomerModel.name) &&
        Objects.equals(this.alias, dkCloudDataModelCustomersCustomerModel.alias) &&
        Objects.equals(this.address1, dkCloudDataModelCustomersCustomerModel.address1) &&
        Objects.equals(this.address2, dkCloudDataModelCustomersCustomerModel.address2) &&
        Objects.equals(this.address3, dkCloudDataModelCustomersCustomerModel.address3) &&
        Objects.equals(this.zipCode, dkCloudDataModelCustomersCustomerModel.zipCode) &&
        Objects.equals(this.balanceAmount, dkCloudDataModelCustomersCustomerModel.balanceAmount) &&
        Objects.equals(this.phone, dkCloudDataModelCustomersCustomerModel.phone) &&
        Objects.equals(this.phoneLocal, dkCloudDataModelCustomersCustomerModel.phoneLocal) &&
        Objects.equals(this.phoneMobile, dkCloudDataModelCustomersCustomerModel.phoneMobile) &&
        Objects.equals(this.phoneFax, dkCloudDataModelCustomersCustomerModel.phoneFax) &&
        Objects.equals(this.countryCode, dkCloudDataModelCustomersCustomerModel.countryCode) &&
        Objects.equals(this.originCountryCode, dkCloudDataModelCustomersCustomerModel.originCountryCode) &&
        Objects.equals(this.email, dkCloudDataModelCustomersCustomerModel.email) &&
        Objects.equals(this.password, dkCloudDataModelCustomersCustomerModel.password) &&
        Objects.equals(this.group, dkCloudDataModelCustomersCustomerModel.group) &&
        Objects.equals(this.salesPerson, dkCloudDataModelCustomersCustomerModel.salesPerson) &&
        Objects.equals(this.discount, dkCloudDataModelCustomersCustomerModel.discount) &&
        Objects.equals(this.useItemRecivers, dkCloudDataModelCustomersCustomerModel.useItemRecivers) &&
        Objects.equals(this.paymentTerm, dkCloudDataModelCustomersCustomerModel.paymentTerm) &&
        Objects.equals(this.paymentMode, dkCloudDataModelCustomersCustomerModel.paymentMode) &&
        Objects.equals(this.currencyCode, dkCloudDataModelCustomersCustomerModel.currencyCode) &&
        Objects.equals(this.noVat, dkCloudDataModelCustomersCustomerModel.noVat) &&
        Objects.equals(this.ledgerCode, dkCloudDataModelCustomersCustomerModel.ledgerCode) &&
        Objects.equals(this.blocked, dkCloudDataModelCustomersCustomerModel.blocked) &&
        Objects.equals(this.gender, dkCloudDataModelCustomersCustomerModel.gender) &&
        Objects.equals(this.priceGroup, dkCloudDataModelCustomersCustomerModel.priceGroup) &&
        Objects.equals(this.billingFee, dkCloudDataModelCustomersCustomerModel.billingFee) &&
        Objects.equals(this.modified, dkCloudDataModelCustomersCustomerModel.modified);
  }

  @Override
  public int hashCode() {
    return Objects.hash(number, deleted, contacts, recivers, memos, properties, changes, attachments, conditions, sendTo, recordID, name, alias, address1, address2, address3, zipCode, balanceAmount, phone, phoneLocal, phoneMobile, phoneFax, countryCode, originCountryCode, email, password, group, salesPerson, discount, useItemRecivers, paymentTerm, paymentMode, currencyCode, noVat, ledgerCode, blocked, gender, priceGroup, billingFee, modified);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DkCloudDataModelCustomersCustomerModel {\n");
    
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    deleted: ").append(toIndentedString(deleted)).append("\n");
    sb.append("    contacts: ").append(toIndentedString(contacts)).append("\n");
    sb.append("    recivers: ").append(toIndentedString(recivers)).append("\n");
    sb.append("    memos: ").append(toIndentedString(memos)).append("\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("    changes: ").append(toIndentedString(changes)).append("\n");
    sb.append("    attachments: ").append(toIndentedString(attachments)).append("\n");
    sb.append("    conditions: ").append(toIndentedString(conditions)).append("\n");
    sb.append("    sendTo: ").append(toIndentedString(sendTo)).append("\n");
    sb.append("    recordID: ").append(toIndentedString(recordID)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    alias: ").append(toIndentedString(alias)).append("\n");
    sb.append("    address1: ").append(toIndentedString(address1)).append("\n");
    sb.append("    address2: ").append(toIndentedString(address2)).append("\n");
    sb.append("    address3: ").append(toIndentedString(address3)).append("\n");
    sb.append("    zipCode: ").append(toIndentedString(zipCode)).append("\n");
    sb.append("    balanceAmount: ").append(toIndentedString(balanceAmount)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    phoneLocal: ").append(toIndentedString(phoneLocal)).append("\n");
    sb.append("    phoneMobile: ").append(toIndentedString(phoneMobile)).append("\n");
    sb.append("    phoneFax: ").append(toIndentedString(phoneFax)).append("\n");
    sb.append("    countryCode: ").append(toIndentedString(countryCode)).append("\n");
    sb.append("    originCountryCode: ").append(toIndentedString(originCountryCode)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    group: ").append(toIndentedString(group)).append("\n");
    sb.append("    salesPerson: ").append(toIndentedString(salesPerson)).append("\n");
    sb.append("    discount: ").append(toIndentedString(discount)).append("\n");
    sb.append("    useItemRecivers: ").append(toIndentedString(useItemRecivers)).append("\n");
    sb.append("    paymentTerm: ").append(toIndentedString(paymentTerm)).append("\n");
    sb.append("    paymentMode: ").append(toIndentedString(paymentMode)).append("\n");
    sb.append("    currencyCode: ").append(toIndentedString(currencyCode)).append("\n");
    sb.append("    noVat: ").append(toIndentedString(noVat)).append("\n");
    sb.append("    ledgerCode: ").append(toIndentedString(ledgerCode)).append("\n");
    sb.append("    blocked: ").append(toIndentedString(blocked)).append("\n");
    sb.append("    gender: ").append(toIndentedString(gender)).append("\n");
    sb.append("    priceGroup: ").append(toIndentedString(priceGroup)).append("\n");
    sb.append("    billingFee: ").append(toIndentedString(billingFee)).append("\n");
    sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

