/*
 * dkPlus.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * DkCloudDataModelCustomersCustomerMemoModel
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-11-12T12:57:09.866Z")



public class DkCloudDataModelCustomersCustomerMemoModel {
  @SerializedName("PageName")
  private String pageName = null;

  @SerializedName("PlainText")
  private String plainText = null;

  @SerializedName("Modified")
  private OffsetDateTime modified = null;

  @SerializedName("RecordID")
  private Long recordID = null;

  public DkCloudDataModelCustomersCustomerMemoModel pageName(String pageName) {
    this.pageName = pageName;
    return this;
  }

   /**
   * Get pageName
   * @return pageName
  **/
  @ApiModelProperty(value = "")
  public String getPageName() {
    return pageName;
  }

  public void setPageName(String pageName) {
    this.pageName = pageName;
  }

  public DkCloudDataModelCustomersCustomerMemoModel plainText(String plainText) {
    this.plainText = plainText;
    return this;
  }

   /**
   * Get plainText
   * @return plainText
  **/
  @ApiModelProperty(value = "")
  public String getPlainText() {
    return plainText;
  }

  public void setPlainText(String plainText) {
    this.plainText = plainText;
  }

  public DkCloudDataModelCustomersCustomerMemoModel modified(OffsetDateTime modified) {
    this.modified = modified;
    return this;
  }

   /**
   * Get modified
   * @return modified
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getModified() {
    return modified;
  }

  public void setModified(OffsetDateTime modified) {
    this.modified = modified;
  }

  public DkCloudDataModelCustomersCustomerMemoModel recordID(Long recordID) {
    this.recordID = recordID;
    return this;
  }

   /**
   * Get recordID
   * @return recordID
  **/
  @ApiModelProperty(value = "")
  public Long getRecordID() {
    return recordID;
  }

  public void setRecordID(Long recordID) {
    this.recordID = recordID;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DkCloudDataModelCustomersCustomerMemoModel dkCloudDataModelCustomersCustomerMemoModel = (DkCloudDataModelCustomersCustomerMemoModel) o;
    return Objects.equals(this.pageName, dkCloudDataModelCustomersCustomerMemoModel.pageName) &&
        Objects.equals(this.plainText, dkCloudDataModelCustomersCustomerMemoModel.plainText) &&
        Objects.equals(this.modified, dkCloudDataModelCustomersCustomerMemoModel.modified) &&
        Objects.equals(this.recordID, dkCloudDataModelCustomersCustomerMemoModel.recordID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pageName, plainText, modified, recordID);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DkCloudDataModelCustomersCustomerMemoModel {\n");
    
    sb.append("    pageName: ").append(toIndentedString(pageName)).append("\n");
    sb.append("    plainText: ").append(toIndentedString(plainText)).append("\n");
    sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
    sb.append("    recordID: ").append(toIndentedString(recordID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

