/*
 * dkPlus.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * DkCloudDataModelProductsCurrencyPriceModel
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-11-12T12:57:09.866Z")



public class DkCloudDataModelProductsCurrencyPriceModel {
  @SerializedName("CurrencyCode")
  private String currencyCode = null;

  @SerializedName("Price1")
  private Double price1 = null;

  @SerializedName("Price2")
  private Double price2 = null;

  @SerializedName("Price3")
  private Double price3 = null;

  public DkCloudDataModelProductsCurrencyPriceModel currencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
    return this;
  }

   /**
   * Get currencyCode
   * @return currencyCode
  **/
  @ApiModelProperty(value = "")
  public String getCurrencyCode() {
    return currencyCode;
  }

  public void setCurrencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
  }

  public DkCloudDataModelProductsCurrencyPriceModel price1(Double price1) {
    this.price1 = price1;
    return this;
  }

   /**
   * Get price1
   * @return price1
  **/
  @ApiModelProperty(value = "")
  public Double getPrice1() {
    return price1;
  }

  public void setPrice1(Double price1) {
    this.price1 = price1;
  }

  public DkCloudDataModelProductsCurrencyPriceModel price2(Double price2) {
    this.price2 = price2;
    return this;
  }

   /**
   * Get price2
   * @return price2
  **/
  @ApiModelProperty(value = "")
  public Double getPrice2() {
    return price2;
  }

  public void setPrice2(Double price2) {
    this.price2 = price2;
  }

  public DkCloudDataModelProductsCurrencyPriceModel price3(Double price3) {
    this.price3 = price3;
    return this;
  }

   /**
   * Get price3
   * @return price3
  **/
  @ApiModelProperty(value = "")
  public Double getPrice3() {
    return price3;
  }

  public void setPrice3(Double price3) {
    this.price3 = price3;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DkCloudDataModelProductsCurrencyPriceModel dkCloudDataModelProductsCurrencyPriceModel = (DkCloudDataModelProductsCurrencyPriceModel) o;
    return Objects.equals(this.currencyCode, dkCloudDataModelProductsCurrencyPriceModel.currencyCode) &&
        Objects.equals(this.price1, dkCloudDataModelProductsCurrencyPriceModel.price1) &&
        Objects.equals(this.price2, dkCloudDataModelProductsCurrencyPriceModel.price2) &&
        Objects.equals(this.price3, dkCloudDataModelProductsCurrencyPriceModel.price3);
  }

  @Override
  public int hashCode() {
    return Objects.hash(currencyCode, price1, price2, price3);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DkCloudDataModelProductsCurrencyPriceModel {\n");
    
    sb.append("    currencyCode: ").append(toIndentedString(currencyCode)).append("\n");
    sb.append("    price1: ").append(toIndentedString(price1)).append("\n");
    sb.append("    price2: ").append(toIndentedString(price2)).append("\n");
    sb.append("    price3: ").append(toIndentedString(price3)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

