/*
 * dkPlus.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.DkCloudDataModelProductsSubCategoryModel;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * DkCloudDataModelProductsCategoriesModel
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-11-12T12:57:09.866Z")



public class DkCloudDataModelProductsCategoriesModel {
  @SerializedName("ID")
  private String ID = null;

  @SerializedName("SubCategories")
  private List<DkCloudDataModelProductsSubCategoryModel> subCategories = null;

  @SerializedName("Description")
  private String description = null;

  @SerializedName("IsActive")
  private Boolean isActive = null;

  public DkCloudDataModelProductsCategoriesModel ID(String ID) {
    this.ID = ID;
    return this;
  }

   /**
   * Get ID
   * @return ID
  **/
  @ApiModelProperty(value = "")
  public String getID() {
    return ID;
  }

  public void setID(String ID) {
    this.ID = ID;
  }

  public DkCloudDataModelProductsCategoriesModel subCategories(List<DkCloudDataModelProductsSubCategoryModel> subCategories) {
    this.subCategories = subCategories;
    return this;
  }

  public DkCloudDataModelProductsCategoriesModel addSubCategoriesItem(DkCloudDataModelProductsSubCategoryModel subCategoriesItem) {
    if (this.subCategories == null) {
      this.subCategories = new ArrayList<DkCloudDataModelProductsSubCategoryModel>();
    }
    this.subCategories.add(subCategoriesItem);
    return this;
  }

   /**
   * Get subCategories
   * @return subCategories
  **/
  @ApiModelProperty(value = "")
  public List<DkCloudDataModelProductsSubCategoryModel> getSubCategories() {
    return subCategories;
  }

  public void setSubCategories(List<DkCloudDataModelProductsSubCategoryModel> subCategories) {
    this.subCategories = subCategories;
  }

  public DkCloudDataModelProductsCategoriesModel description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public DkCloudDataModelProductsCategoriesModel isActive(Boolean isActive) {
    this.isActive = isActive;
    return this;
  }

   /**
   * Get isActive
   * @return isActive
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsActive() {
    return isActive;
  }

  public void setIsActive(Boolean isActive) {
    this.isActive = isActive;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DkCloudDataModelProductsCategoriesModel dkCloudDataModelProductsCategoriesModel = (DkCloudDataModelProductsCategoriesModel) o;
    return Objects.equals(this.ID, dkCloudDataModelProductsCategoriesModel.ID) &&
        Objects.equals(this.subCategories, dkCloudDataModelProductsCategoriesModel.subCategories) &&
        Objects.equals(this.description, dkCloudDataModelProductsCategoriesModel.description) &&
        Objects.equals(this.isActive, dkCloudDataModelProductsCategoriesModel.isActive);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ID, subCategories, description, isActive);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DkCloudDataModelProductsCategoriesModel {\n");
    
    sb.append("    ID: ").append(toIndentedString(ID)).append("\n");
    sb.append("    subCategories: ").append(toIndentedString(subCategories)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    isActive: ").append(toIndentedString(isActive)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

