/*
 * dkPlus.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * DkCloudDataModelMembersStatistics
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-11-12T12:57:09.866Z")



public class DkCloudDataModelMembersStatistics {
  @SerializedName("MemberAge")
  private Double memberAge = null;

  @SerializedName("CareerAge")
  private Double careerAge = null;

  @SerializedName("ExtraProperties")
  private Map<String, String> extraProperties = null;

  public DkCloudDataModelMembersStatistics memberAge(Double memberAge) {
    this.memberAge = memberAge;
    return this;
  }

   /**
   * Get memberAge
   * @return memberAge
  **/
  @ApiModelProperty(value = "")
  public Double getMemberAge() {
    return memberAge;
  }

  public void setMemberAge(Double memberAge) {
    this.memberAge = memberAge;
  }

  public DkCloudDataModelMembersStatistics careerAge(Double careerAge) {
    this.careerAge = careerAge;
    return this;
  }

   /**
   * Get careerAge
   * @return careerAge
  **/
  @ApiModelProperty(value = "")
  public Double getCareerAge() {
    return careerAge;
  }

  public void setCareerAge(Double careerAge) {
    this.careerAge = careerAge;
  }

  public DkCloudDataModelMembersStatistics extraProperties(Map<String, String> extraProperties) {
    this.extraProperties = extraProperties;
    return this;
  }

  public DkCloudDataModelMembersStatistics putExtraPropertiesItem(String key, String extraPropertiesItem) {
    if (this.extraProperties == null) {
      this.extraProperties = new HashMap<String, String>();
    }
    this.extraProperties.put(key, extraPropertiesItem);
    return this;
  }

   /**
   * Get extraProperties
   * @return extraProperties
  **/
  @ApiModelProperty(value = "")
  public Map<String, String> getExtraProperties() {
    return extraProperties;
  }

  public void setExtraProperties(Map<String, String> extraProperties) {
    this.extraProperties = extraProperties;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DkCloudDataModelMembersStatistics dkCloudDataModelMembersStatistics = (DkCloudDataModelMembersStatistics) o;
    return Objects.equals(this.memberAge, dkCloudDataModelMembersStatistics.memberAge) &&
        Objects.equals(this.careerAge, dkCloudDataModelMembersStatistics.careerAge) &&
        Objects.equals(this.extraProperties, dkCloudDataModelMembersStatistics.extraProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(memberAge, careerAge, extraProperties);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DkCloudDataModelMembersStatistics {\n");
    
    sb.append("    memberAge: ").append(toIndentedString(memberAge)).append("\n");
    sb.append("    careerAge: ").append(toIndentedString(careerAge)).append("\n");
    sb.append("    extraProperties: ").append(toIndentedString(extraProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

