/*
 * dkPlus.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.DkPlusAPIModelsInvoicePaymentPlanCard;
import io.swagger.client.model.DkPlusAPIModelsInvoicePaymentPlanTransaction;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Create Payment Plan Model
 */
@ApiModel(description = "Create Payment Plan Model")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-11-12T12:57:09.866Z")



public class DkPlusAPIModelsInvoicePaymentPlanCreate {
  @SerializedName("Description")
  private String description = null;

  @SerializedName("Amount")
  private Double amount = null;

  @SerializedName("NetAmount")
  private Double netAmount = null;

  @SerializedName("Transactions")
  private List<DkPlusAPIModelsInvoicePaymentPlanTransaction> transactions = new ArrayList<DkPlusAPIModelsInvoicePaymentPlanTransaction>();

  @SerializedName("Reference")
  private String reference = null;

  @SerializedName("Card")
  private DkPlusAPIModelsInvoicePaymentPlanCard card = null;

  @SerializedName("SenderId")
  private String senderId = null;

  public DkPlusAPIModelsInvoicePaymentPlanCreate description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Payment plan description
   * @return description
  **/
  @ApiModelProperty(required = true, value = "Payment plan description")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public DkPlusAPIModelsInvoicePaymentPlanCreate amount(Double amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Netto Invoice Amount
   * @return amount
  **/
  @ApiModelProperty(required = true, value = "Netto Invoice Amount")
  public Double getAmount() {
    return amount;
  }

  public void setAmount(Double amount) {
    this.amount = amount;
  }

  public DkPlusAPIModelsInvoicePaymentPlanCreate netAmount(Double netAmount) {
    this.netAmount = netAmount;
    return this;
  }

   /**
   * Net amount of invoice
   * @return netAmount
  **/
  @ApiModelProperty(value = "Net amount of invoice")
  public Double getNetAmount() {
    return netAmount;
  }

  public void setNetAmount(Double netAmount) {
    this.netAmount = netAmount;
  }

  public DkPlusAPIModelsInvoicePaymentPlanCreate transactions(List<DkPlusAPIModelsInvoicePaymentPlanTransaction> transactions) {
    this.transactions = transactions;
    return this;
  }

  public DkPlusAPIModelsInvoicePaymentPlanCreate addTransactionsItem(DkPlusAPIModelsInvoicePaymentPlanTransaction transactionsItem) {
    this.transactions.add(transactionsItem);
    return this;
  }

   /**
   * Breakdown of payment transactions when to process
   * @return transactions
  **/
  @ApiModelProperty(required = true, value = "Breakdown of payment transactions when to process")
  public List<DkPlusAPIModelsInvoicePaymentPlanTransaction> getTransactions() {
    return transactions;
  }

  public void setTransactions(List<DkPlusAPIModelsInvoicePaymentPlanTransaction> transactions) {
    this.transactions = transactions;
  }

  public DkPlusAPIModelsInvoicePaymentPlanCreate reference(String reference) {
    this.reference = reference;
    return this;
  }

   /**
   * Plan External Reference Id
   * @return reference
  **/
  @ApiModelProperty(value = "Plan External Reference Id")
  public String getReference() {
    return reference;
  }

  public void setReference(String reference) {
    this.reference = reference;
  }

  public DkPlusAPIModelsInvoicePaymentPlanCreate card(DkPlusAPIModelsInvoicePaymentPlanCard card) {
    this.card = card;
    return this;
  }

   /**
   * Card to use for Payment Plan
   * @return card
  **/
  @ApiModelProperty(required = true, value = "Card to use for Payment Plan")
  public DkPlusAPIModelsInvoicePaymentPlanCard getCard() {
    return card;
  }

  public void setCard(DkPlusAPIModelsInvoicePaymentPlanCard card) {
    this.card = card;
  }

  public DkPlusAPIModelsInvoicePaymentPlanCreate senderId(String senderId) {
    this.senderId = senderId;
    return this;
  }

   /**
   * Sender Provider Id
   * @return senderId
  **/
  @ApiModelProperty(required = true, value = "Sender Provider Id")
  public String getSenderId() {
    return senderId;
  }

  public void setSenderId(String senderId) {
    this.senderId = senderId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DkPlusAPIModelsInvoicePaymentPlanCreate dkPlusAPIModelsInvoicePaymentPlanCreate = (DkPlusAPIModelsInvoicePaymentPlanCreate) o;
    return Objects.equals(this.description, dkPlusAPIModelsInvoicePaymentPlanCreate.description) &&
        Objects.equals(this.amount, dkPlusAPIModelsInvoicePaymentPlanCreate.amount) &&
        Objects.equals(this.netAmount, dkPlusAPIModelsInvoicePaymentPlanCreate.netAmount) &&
        Objects.equals(this.transactions, dkPlusAPIModelsInvoicePaymentPlanCreate.transactions) &&
        Objects.equals(this.reference, dkPlusAPIModelsInvoicePaymentPlanCreate.reference) &&
        Objects.equals(this.card, dkPlusAPIModelsInvoicePaymentPlanCreate.card) &&
        Objects.equals(this.senderId, dkPlusAPIModelsInvoicePaymentPlanCreate.senderId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, amount, netAmount, transactions, reference, card, senderId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DkPlusAPIModelsInvoicePaymentPlanCreate {\n");
    
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    netAmount: ").append(toIndentedString(netAmount)).append("\n");
    sb.append("    transactions: ").append(toIndentedString(transactions)).append("\n");
    sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
    sb.append("    card: ").append(toIndentedString(card)).append("\n");
    sb.append("    senderId: ").append(toIndentedString(senderId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

