/*
 * dkPlus.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.DkPlusAPIModelsProductInventoryJournalLine;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;

/**
 * Inventory Journal
 */
@ApiModel(description = "Inventory Journal")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-11-12T12:57:09.866Z")



public class DkPlusAPIModelsProductInventoryJournal {
  @SerializedName("Date")
  private OffsetDateTime date = null;

  @SerializedName("Description")
  private String description = null;

  @SerializedName("Lines")
  private List<DkPlusAPIModelsProductInventoryJournalLine> lines = null;

  public DkPlusAPIModelsProductInventoryJournal date(OffsetDateTime date) {
    this.date = date;
    return this;
  }

   /**
   * Journal Date
   * @return date
  **/
  @ApiModelProperty(value = "Journal Date")
  public OffsetDateTime getDate() {
    return date;
  }

  public void setDate(OffsetDateTime date) {
    this.date = date;
  }

  public DkPlusAPIModelsProductInventoryJournal description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Journal Description
   * @return description
  **/
  @ApiModelProperty(value = "Journal Description")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public DkPlusAPIModelsProductInventoryJournal lines(List<DkPlusAPIModelsProductInventoryJournalLine> lines) {
    this.lines = lines;
    return this;
  }

  public DkPlusAPIModelsProductInventoryJournal addLinesItem(DkPlusAPIModelsProductInventoryJournalLine linesItem) {
    if (this.lines == null) {
      this.lines = new ArrayList<DkPlusAPIModelsProductInventoryJournalLine>();
    }
    this.lines.add(linesItem);
    return this;
  }

   /**
   * Journal Lines
   * @return lines
  **/
  @ApiModelProperty(value = "Journal Lines")
  public List<DkPlusAPIModelsProductInventoryJournalLine> getLines() {
    return lines;
  }

  public void setLines(List<DkPlusAPIModelsProductInventoryJournalLine> lines) {
    this.lines = lines;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DkPlusAPIModelsProductInventoryJournal dkPlusAPIModelsProductInventoryJournal = (DkPlusAPIModelsProductInventoryJournal) o;
    return Objects.equals(this.date, dkPlusAPIModelsProductInventoryJournal.date) &&
        Objects.equals(this.description, dkPlusAPIModelsProductInventoryJournal.description) &&
        Objects.equals(this.lines, dkPlusAPIModelsProductInventoryJournal.lines);
  }

  @Override
  public int hashCode() {
    return Objects.hash(date, description, lines);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DkPlusAPIModelsProductInventoryJournal {\n");
    
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    lines: ").append(toIndentedString(lines)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

