/*
 * dkPlus.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * Employee Work Journal Entry
 */
@ApiModel(description = "Employee Work Journal Entry")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-11-12T12:57:09.866Z")



public class DkPlusAPIModelsEmployeeEmployeeWork {
  @SerializedName("Date")
  private OffsetDateTime date = null;

  @SerializedName("Text")
  private String text = null;

  @SerializedName("Project")
  private String project = null;

  @SerializedName("Phase")
  private String phase = null;

  @SerializedName("Task")
  private String task = null;

  @SerializedName("DayTime")
  private Double dayTime = null;

  @SerializedName("DriveTime")
  private Double driveTime = null;

  @SerializedName("OverTime")
  private Double overTime = null;

  @SerializedName("Billable")
  private Boolean billable = null;

  public DkPlusAPIModelsEmployeeEmployeeWork date(OffsetDateTime date) {
    this.date = date;
    return this;
  }

   /**
   * Entry Date
   * @return date
  **/
  @ApiModelProperty(value = "Entry Date")
  public OffsetDateTime getDate() {
    return date;
  }

  public void setDate(OffsetDateTime date) {
    this.date = date;
  }

  public DkPlusAPIModelsEmployeeEmployeeWork text(String text) {
    this.text = text;
    return this;
  }

   /**
   * Description, if not supplied will be auto populated by dk rules
   * @return text
  **/
  @ApiModelProperty(value = "Description, if not supplied will be auto populated by dk rules")
  public String getText() {
    return text;
  }

  public void setText(String text) {
    this.text = text;
  }

  public DkPlusAPIModelsEmployeeEmployeeWork project(String project) {
    this.project = project;
    return this;
  }

   /**
   * Project Number
   * @return project
  **/
  @ApiModelProperty(required = true, value = "Project Number")
  public String getProject() {
    return project;
  }

  public void setProject(String project) {
    this.project = project;
  }

  public DkPlusAPIModelsEmployeeEmployeeWork phase(String phase) {
    this.phase = phase;
    return this;
  }

   /**
   * Project Phase Number
   * @return phase
  **/
  @ApiModelProperty(value = "Project Phase Number")
  public String getPhase() {
    return phase;
  }

  public void setPhase(String phase) {
    this.phase = phase;
  }

  public DkPlusAPIModelsEmployeeEmployeeWork task(String task) {
    this.task = task;
    return this;
  }

   /**
   * Project Task Number
   * @return task
  **/
  @ApiModelProperty(value = "Project Task Number")
  public String getTask() {
    return task;
  }

  public void setTask(String task) {
    this.task = task;
  }

  public DkPlusAPIModelsEmployeeEmployeeWork dayTime(Double dayTime) {
    this.dayTime = dayTime;
    return this;
  }

   /**
   * Number of work hours (Day)
   * @return dayTime
  **/
  @ApiModelProperty(value = "Number of work hours (Day)")
  public Double getDayTime() {
    return dayTime;
  }

  public void setDayTime(Double dayTime) {
    this.dayTime = dayTime;
  }

  public DkPlusAPIModelsEmployeeEmployeeWork driveTime(Double driveTime) {
    this.driveTime = driveTime;
    return this;
  }

   /**
   * Quantity Drive Time
   * @return driveTime
  **/
  @ApiModelProperty(value = "Quantity Drive Time")
  public Double getDriveTime() {
    return driveTime;
  }

  public void setDriveTime(Double driveTime) {
    this.driveTime = driveTime;
  }

  public DkPlusAPIModelsEmployeeEmployeeWork overTime(Double overTime) {
    this.overTime = overTime;
    return this;
  }

   /**
   * Number of Work Hours(Over Time)
   * @return overTime
  **/
  @ApiModelProperty(value = "Number of Work Hours(Over Time)")
  public Double getOverTime() {
    return overTime;
  }

  public void setOverTime(Double overTime) {
    this.overTime = overTime;
  }

  public DkPlusAPIModelsEmployeeEmployeeWork billable(Boolean billable) {
    this.billable = billable;
    return this;
  }

   /**
   * Should Entry be billed
   * @return billable
  **/
  @ApiModelProperty(value = "Should Entry be billed")
  public Boolean isBillable() {
    return billable;
  }

  public void setBillable(Boolean billable) {
    this.billable = billable;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DkPlusAPIModelsEmployeeEmployeeWork dkPlusAPIModelsEmployeeEmployeeWork = (DkPlusAPIModelsEmployeeEmployeeWork) o;
    return Objects.equals(this.date, dkPlusAPIModelsEmployeeEmployeeWork.date) &&
        Objects.equals(this.text, dkPlusAPIModelsEmployeeEmployeeWork.text) &&
        Objects.equals(this.project, dkPlusAPIModelsEmployeeEmployeeWork.project) &&
        Objects.equals(this.phase, dkPlusAPIModelsEmployeeEmployeeWork.phase) &&
        Objects.equals(this.task, dkPlusAPIModelsEmployeeEmployeeWork.task) &&
        Objects.equals(this.dayTime, dkPlusAPIModelsEmployeeEmployeeWork.dayTime) &&
        Objects.equals(this.driveTime, dkPlusAPIModelsEmployeeEmployeeWork.driveTime) &&
        Objects.equals(this.overTime, dkPlusAPIModelsEmployeeEmployeeWork.overTime) &&
        Objects.equals(this.billable, dkPlusAPIModelsEmployeeEmployeeWork.billable);
  }

  @Override
  public int hashCode() {
    return Objects.hash(date, text, project, phase, task, dayTime, driveTime, overTime, billable);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DkPlusAPIModelsEmployeeEmployeeWork {\n");
    
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    project: ").append(toIndentedString(project)).append("\n");
    sb.append("    phase: ").append(toIndentedString(phase)).append("\n");
    sb.append("    task: ").append(toIndentedString(task)).append("\n");
    sb.append("    dayTime: ").append(toIndentedString(dayTime)).append("\n");
    sb.append("    driveTime: ").append(toIndentedString(driveTime)).append("\n");
    sb.append("    overTime: ").append(toIndentedString(overTime)).append("\n");
    sb.append("    billable: ").append(toIndentedString(billable)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

