/*
 * dkPlus.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.DkCloudDataModelCustomersCustomerModel;
import io.swagger.client.model.DkCloudDataModelCustomersItemReciverModel;
import io.swagger.client.model.DkCloudDataModelSalesSalesOrderLineModel;
import io.swagger.client.model.DkPlusAPIModelsInvoiceContact;
import io.swagger.client.model.DkPlusAPIModelsInvoiceReceiver;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.threeten.bp.OffsetDateTime;

/**
 * DkPlusAPIModelsOrderHead
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-11-12T12:57:09.866Z")



public class DkPlusAPIModelsOrderHead {
  @SerializedName("Warehouse")
  private String warehouse = null;

  @SerializedName("Receiver")
  private DkPlusAPIModelsInvoiceReceiver receiver = null;

  @SerializedName("Contact")
  private DkPlusAPIModelsInvoiceContact contact = null;

  @SerializedName("Properties")
  private Map<String, String> properties = null;

  @SerializedName("Number")
  private Integer number = null;

  @SerializedName("Customer")
  private DkCloudDataModelCustomersCustomerModel customer = null;

  @SerializedName("CContact")
  private String ccontact = null;

  @SerializedName("ID")
  private Integer ID = null;

  @SerializedName("OrderDate")
  private OffsetDateTime orderDate = null;

  @SerializedName("TotalAmount")
  private Double totalAmount = null;

  @SerializedName("Currency")
  private String currency = null;

  @SerializedName("Reference")
  private String reference = null;

  @SerializedName("SettledType")
  private Integer settledType = null;

  @SerializedName("SettledAmount")
  private Double settledAmount = null;

  @SerializedName("SalePerson")
  private String salePerson = null;

  @SerializedName("Text1")
  private String text1 = null;

  @SerializedName("Text2")
  private String text2 = null;

  @SerializedName("Dim1")
  private String dim1 = null;

  @SerializedName("Origin")
  private Integer origin = null;

  @SerializedName("PaymentTerm")
  private String paymentTerm = null;

  @SerializedName("ClaimStatus")
  private Integer claimStatus = null;

  @SerializedName("Exchange")
  private Double exchange = null;

  /**
   * Gets or Sets status
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    INPROCESS("InProcess"),
    
    SENT("Sent"),
    
    PARTHANDLED("PartHandled"),
    
    HANDLED("Handled"),
    
    ONHOLD("OnHold"),
    
    CANCELED("Canceled");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String text) {
      for (StatusEnum b : StatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return StatusEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("Status")
  private StatusEnum status = null;

  /**
   * Gets or Sets deliveryStatus
   */
  @JsonAdapter(DeliveryStatusEnum.Adapter.class)
  public enum DeliveryStatusEnum {
    INPROCESS("InProcess"),
    
    READY("Ready"),
    
    HURRY("Hurry"),
    
    WAIT("Wait"),
    
    REQUEST("Request");

    private String value;

    DeliveryStatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static DeliveryStatusEnum fromValue(String text) {
      for (DeliveryStatusEnum b : DeliveryStatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<DeliveryStatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final DeliveryStatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public DeliveryStatusEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return DeliveryStatusEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("DeliveryStatus")
  private DeliveryStatusEnum deliveryStatus = null;

  @SerializedName("DeliverTo")
  private DkCloudDataModelCustomersItemReciverModel deliverTo = null;

  @SerializedName("Lines")
  private List<DkCloudDataModelSalesSalesOrderLineModel> lines = null;

  public DkPlusAPIModelsOrderHead warehouse(String warehouse) {
    this.warehouse = warehouse;
    return this;
  }

   /**
   * Warehouse
   * @return warehouse
  **/
  @ApiModelProperty(value = "Warehouse")
  public String getWarehouse() {
    return warehouse;
  }

  public void setWarehouse(String warehouse) {
    this.warehouse = warehouse;
  }

  public DkPlusAPIModelsOrderHead receiver(DkPlusAPIModelsInvoiceReceiver receiver) {
    this.receiver = receiver;
    return this;
  }

   /**
   * Item Receiver
   * @return receiver
  **/
  @ApiModelProperty(value = "Item Receiver")
  public DkPlusAPIModelsInvoiceReceiver getReceiver() {
    return receiver;
  }

  public void setReceiver(DkPlusAPIModelsInvoiceReceiver receiver) {
    this.receiver = receiver;
  }

  public DkPlusAPIModelsOrderHead contact(DkPlusAPIModelsInvoiceContact contact) {
    this.contact = contact;
    return this;
  }

   /**
   * Contact
   * @return contact
  **/
  @ApiModelProperty(value = "Contact")
  public DkPlusAPIModelsInvoiceContact getContact() {
    return contact;
  }

  public void setContact(DkPlusAPIModelsInvoiceContact contact) {
    this.contact = contact;
  }

  public DkPlusAPIModelsOrderHead properties(Map<String, String> properties) {
    this.properties = properties;
    return this;
  }

  public DkPlusAPIModelsOrderHead putPropertiesItem(String key, String propertiesItem) {
    if (this.properties == null) {
      this.properties = new HashMap<String, String>();
    }
    this.properties.put(key, propertiesItem);
    return this;
  }

   /**
   * Additional Properties
   * @return properties
  **/
  @ApiModelProperty(value = "Additional Properties")
  public Map<String, String> getProperties() {
    return properties;
  }

  public void setProperties(Map<String, String> properties) {
    this.properties = properties;
  }

  public DkPlusAPIModelsOrderHead number(Integer number) {
    this.number = number;
    return this;
  }

   /**
   * Get number
   * @return number
  **/
  @ApiModelProperty(value = "")
  public Integer getNumber() {
    return number;
  }

  public void setNumber(Integer number) {
    this.number = number;
  }

  public DkPlusAPIModelsOrderHead customer(DkCloudDataModelCustomersCustomerModel customer) {
    this.customer = customer;
    return this;
  }

   /**
   * Get customer
   * @return customer
  **/
  @ApiModelProperty(required = true, value = "")
  public DkCloudDataModelCustomersCustomerModel getCustomer() {
    return customer;
  }

  public void setCustomer(DkCloudDataModelCustomersCustomerModel customer) {
    this.customer = customer;
  }

  public DkPlusAPIModelsOrderHead ccontact(String ccontact) {
    this.ccontact = ccontact;
    return this;
  }

   /**
   * Get ccontact
   * @return ccontact
  **/
  @ApiModelProperty(value = "")
  public String getCcontact() {
    return ccontact;
  }

  public void setCcontact(String ccontact) {
    this.ccontact = ccontact;
  }

  public DkPlusAPIModelsOrderHead ID(Integer ID) {
    this.ID = ID;
    return this;
  }

   /**
   * Get ID
   * @return ID
  **/
  @ApiModelProperty(value = "")
  public Integer getID() {
    return ID;
  }

  public void setID(Integer ID) {
    this.ID = ID;
  }

  public DkPlusAPIModelsOrderHead orderDate(OffsetDateTime orderDate) {
    this.orderDate = orderDate;
    return this;
  }

   /**
   * Get orderDate
   * @return orderDate
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getOrderDate() {
    return orderDate;
  }

  public void setOrderDate(OffsetDateTime orderDate) {
    this.orderDate = orderDate;
  }

  public DkPlusAPIModelsOrderHead totalAmount(Double totalAmount) {
    this.totalAmount = totalAmount;
    return this;
  }

   /**
   * Get totalAmount
   * @return totalAmount
  **/
  @ApiModelProperty(value = "")
  public Double getTotalAmount() {
    return totalAmount;
  }

  public void setTotalAmount(Double totalAmount) {
    this.totalAmount = totalAmount;
  }

  public DkPlusAPIModelsOrderHead currency(String currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Get currency
   * @return currency
  **/
  @ApiModelProperty(value = "")
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }

  public DkPlusAPIModelsOrderHead reference(String reference) {
    this.reference = reference;
    return this;
  }

   /**
   * Get reference
   * @return reference
  **/
  @ApiModelProperty(value = "")
  public String getReference() {
    return reference;
  }

  public void setReference(String reference) {
    this.reference = reference;
  }

  public DkPlusAPIModelsOrderHead settledType(Integer settledType) {
    this.settledType = settledType;
    return this;
  }

   /**
   * Get settledType
   * @return settledType
  **/
  @ApiModelProperty(value = "")
  public Integer getSettledType() {
    return settledType;
  }

  public void setSettledType(Integer settledType) {
    this.settledType = settledType;
  }

  public DkPlusAPIModelsOrderHead settledAmount(Double settledAmount) {
    this.settledAmount = settledAmount;
    return this;
  }

   /**
   * Get settledAmount
   * @return settledAmount
  **/
  @ApiModelProperty(value = "")
  public Double getSettledAmount() {
    return settledAmount;
  }

  public void setSettledAmount(Double settledAmount) {
    this.settledAmount = settledAmount;
  }

  public DkPlusAPIModelsOrderHead salePerson(String salePerson) {
    this.salePerson = salePerson;
    return this;
  }

   /**
   * Get salePerson
   * @return salePerson
  **/
  @ApiModelProperty(value = "")
  public String getSalePerson() {
    return salePerson;
  }

  public void setSalePerson(String salePerson) {
    this.salePerson = salePerson;
  }

  public DkPlusAPIModelsOrderHead text1(String text1) {
    this.text1 = text1;
    return this;
  }

   /**
   * Get text1
   * @return text1
  **/
  @ApiModelProperty(value = "")
  public String getText1() {
    return text1;
  }

  public void setText1(String text1) {
    this.text1 = text1;
  }

  public DkPlusAPIModelsOrderHead text2(String text2) {
    this.text2 = text2;
    return this;
  }

   /**
   * Get text2
   * @return text2
  **/
  @ApiModelProperty(value = "")
  public String getText2() {
    return text2;
  }

  public void setText2(String text2) {
    this.text2 = text2;
  }

  public DkPlusAPIModelsOrderHead dim1(String dim1) {
    this.dim1 = dim1;
    return this;
  }

   /**
   * Get dim1
   * @return dim1
  **/
  @ApiModelProperty(value = "")
  public String getDim1() {
    return dim1;
  }

  public void setDim1(String dim1) {
    this.dim1 = dim1;
  }

  public DkPlusAPIModelsOrderHead origin(Integer origin) {
    this.origin = origin;
    return this;
  }

   /**
   * Get origin
   * @return origin
  **/
  @ApiModelProperty(value = "")
  public Integer getOrigin() {
    return origin;
  }

  public void setOrigin(Integer origin) {
    this.origin = origin;
  }

  public DkPlusAPIModelsOrderHead paymentTerm(String paymentTerm) {
    this.paymentTerm = paymentTerm;
    return this;
  }

   /**
   * Get paymentTerm
   * @return paymentTerm
  **/
  @ApiModelProperty(value = "")
  public String getPaymentTerm() {
    return paymentTerm;
  }

  public void setPaymentTerm(String paymentTerm) {
    this.paymentTerm = paymentTerm;
  }

  public DkPlusAPIModelsOrderHead claimStatus(Integer claimStatus) {
    this.claimStatus = claimStatus;
    return this;
  }

   /**
   * Get claimStatus
   * @return claimStatus
  **/
  @ApiModelProperty(value = "")
  public Integer getClaimStatus() {
    return claimStatus;
  }

  public void setClaimStatus(Integer claimStatus) {
    this.claimStatus = claimStatus;
  }

  public DkPlusAPIModelsOrderHead exchange(Double exchange) {
    this.exchange = exchange;
    return this;
  }

   /**
   * Get exchange
   * @return exchange
  **/
  @ApiModelProperty(value = "")
  public Double getExchange() {
    return exchange;
  }

  public void setExchange(Double exchange) {
    this.exchange = exchange;
  }

  public DkPlusAPIModelsOrderHead status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public DkPlusAPIModelsOrderHead deliveryStatus(DeliveryStatusEnum deliveryStatus) {
    this.deliveryStatus = deliveryStatus;
    return this;
  }

   /**
   * Get deliveryStatus
   * @return deliveryStatus
  **/
  @ApiModelProperty(value = "")
  public DeliveryStatusEnum getDeliveryStatus() {
    return deliveryStatus;
  }

  public void setDeliveryStatus(DeliveryStatusEnum deliveryStatus) {
    this.deliveryStatus = deliveryStatus;
  }

  public DkPlusAPIModelsOrderHead deliverTo(DkCloudDataModelCustomersItemReciverModel deliverTo) {
    this.deliverTo = deliverTo;
    return this;
  }

   /**
   * Get deliverTo
   * @return deliverTo
  **/
  @ApiModelProperty(value = "")
  public DkCloudDataModelCustomersItemReciverModel getDeliverTo() {
    return deliverTo;
  }

  public void setDeliverTo(DkCloudDataModelCustomersItemReciverModel deliverTo) {
    this.deliverTo = deliverTo;
  }

  public DkPlusAPIModelsOrderHead lines(List<DkCloudDataModelSalesSalesOrderLineModel> lines) {
    this.lines = lines;
    return this;
  }

  public DkPlusAPIModelsOrderHead addLinesItem(DkCloudDataModelSalesSalesOrderLineModel linesItem) {
    if (this.lines == null) {
      this.lines = new ArrayList<DkCloudDataModelSalesSalesOrderLineModel>();
    }
    this.lines.add(linesItem);
    return this;
  }

   /**
   * Get lines
   * @return lines
  **/
  @ApiModelProperty(value = "")
  public List<DkCloudDataModelSalesSalesOrderLineModel> getLines() {
    return lines;
  }

  public void setLines(List<DkCloudDataModelSalesSalesOrderLineModel> lines) {
    this.lines = lines;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DkPlusAPIModelsOrderHead dkPlusAPIModelsOrderHead = (DkPlusAPIModelsOrderHead) o;
    return Objects.equals(this.warehouse, dkPlusAPIModelsOrderHead.warehouse) &&
        Objects.equals(this.receiver, dkPlusAPIModelsOrderHead.receiver) &&
        Objects.equals(this.contact, dkPlusAPIModelsOrderHead.contact) &&
        Objects.equals(this.properties, dkPlusAPIModelsOrderHead.properties) &&
        Objects.equals(this.number, dkPlusAPIModelsOrderHead.number) &&
        Objects.equals(this.customer, dkPlusAPIModelsOrderHead.customer) &&
        Objects.equals(this.ccontact, dkPlusAPIModelsOrderHead.ccontact) &&
        Objects.equals(this.ID, dkPlusAPIModelsOrderHead.ID) &&
        Objects.equals(this.orderDate, dkPlusAPIModelsOrderHead.orderDate) &&
        Objects.equals(this.totalAmount, dkPlusAPIModelsOrderHead.totalAmount) &&
        Objects.equals(this.currency, dkPlusAPIModelsOrderHead.currency) &&
        Objects.equals(this.reference, dkPlusAPIModelsOrderHead.reference) &&
        Objects.equals(this.settledType, dkPlusAPIModelsOrderHead.settledType) &&
        Objects.equals(this.settledAmount, dkPlusAPIModelsOrderHead.settledAmount) &&
        Objects.equals(this.salePerson, dkPlusAPIModelsOrderHead.salePerson) &&
        Objects.equals(this.text1, dkPlusAPIModelsOrderHead.text1) &&
        Objects.equals(this.text2, dkPlusAPIModelsOrderHead.text2) &&
        Objects.equals(this.dim1, dkPlusAPIModelsOrderHead.dim1) &&
        Objects.equals(this.origin, dkPlusAPIModelsOrderHead.origin) &&
        Objects.equals(this.paymentTerm, dkPlusAPIModelsOrderHead.paymentTerm) &&
        Objects.equals(this.claimStatus, dkPlusAPIModelsOrderHead.claimStatus) &&
        Objects.equals(this.exchange, dkPlusAPIModelsOrderHead.exchange) &&
        Objects.equals(this.status, dkPlusAPIModelsOrderHead.status) &&
        Objects.equals(this.deliveryStatus, dkPlusAPIModelsOrderHead.deliveryStatus) &&
        Objects.equals(this.deliverTo, dkPlusAPIModelsOrderHead.deliverTo) &&
        Objects.equals(this.lines, dkPlusAPIModelsOrderHead.lines);
  }

  @Override
  public int hashCode() {
    return Objects.hash(warehouse, receiver, contact, properties, number, customer, ccontact, ID, orderDate, totalAmount, currency, reference, settledType, settledAmount, salePerson, text1, text2, dim1, origin, paymentTerm, claimStatus, exchange, status, deliveryStatus, deliverTo, lines);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DkPlusAPIModelsOrderHead {\n");
    
    sb.append("    warehouse: ").append(toIndentedString(warehouse)).append("\n");
    sb.append("    receiver: ").append(toIndentedString(receiver)).append("\n");
    sb.append("    contact: ").append(toIndentedString(contact)).append("\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    customer: ").append(toIndentedString(customer)).append("\n");
    sb.append("    ccontact: ").append(toIndentedString(ccontact)).append("\n");
    sb.append("    ID: ").append(toIndentedString(ID)).append("\n");
    sb.append("    orderDate: ").append(toIndentedString(orderDate)).append("\n");
    sb.append("    totalAmount: ").append(toIndentedString(totalAmount)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
    sb.append("    settledType: ").append(toIndentedString(settledType)).append("\n");
    sb.append("    settledAmount: ").append(toIndentedString(settledAmount)).append("\n");
    sb.append("    salePerson: ").append(toIndentedString(salePerson)).append("\n");
    sb.append("    text1: ").append(toIndentedString(text1)).append("\n");
    sb.append("    text2: ").append(toIndentedString(text2)).append("\n");
    sb.append("    dim1: ").append(toIndentedString(dim1)).append("\n");
    sb.append("    origin: ").append(toIndentedString(origin)).append("\n");
    sb.append("    paymentTerm: ").append(toIndentedString(paymentTerm)).append("\n");
    sb.append("    claimStatus: ").append(toIndentedString(claimStatus)).append("\n");
    sb.append("    exchange: ").append(toIndentedString(exchange)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    deliveryStatus: ").append(toIndentedString(deliveryStatus)).append("\n");
    sb.append("    deliverTo: ").append(toIndentedString(deliverTo)).append("\n");
    sb.append("    lines: ").append(toIndentedString(lines)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

