/*
 * dkPlus.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.UUID;
import org.threeten.bp.OffsetDateTime;

/**
 * My Pages User Account
 */
@ApiModel(description = "My Pages User Account")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-11-12T12:57:09.866Z")



public class DkPlusAPIModelsMyPageInvite {
  @SerializedName("Id")
  private UUID id = null;

  @SerializedName("Email")
  private String email = null;

  @SerializedName("Company")
  private String company = null;

  @SerializedName("Expires")
  private OffsetDateTime expires = null;

  @SerializedName("Revoked")
  private Boolean revoked = null;

  @SerializedName("Confirmed")
  private Boolean confirmed = null;

  public DkPlusAPIModelsMyPageInvite id(UUID id) {
    this.id = id;
    return this;
  }

   /**
   * Account Id
   * @return id
  **/
  @ApiModelProperty(example = "00000000-0000-0000-0000-000000000000", value = "Account Id")
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public DkPlusAPIModelsMyPageInvite email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Email
   * @return email
  **/
  @ApiModelProperty(value = "Email")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public DkPlusAPIModelsMyPageInvite company(String company) {
    this.company = company;
    return this;
  }

   /**
   * Company Name
   * @return company
  **/
  @ApiModelProperty(value = "Company Name")
  public String getCompany() {
    return company;
  }

  public void setCompany(String company) {
    this.company = company;
  }

  public DkPlusAPIModelsMyPageInvite expires(OffsetDateTime expires) {
    this.expires = expires;
    return this;
  }

   /**
   * Invite Expires After
   * @return expires
  **/
  @ApiModelProperty(value = "Invite Expires After")
  public OffsetDateTime getExpires() {
    return expires;
  }

  public void setExpires(OffsetDateTime expires) {
    this.expires = expires;
  }

  public DkPlusAPIModelsMyPageInvite revoked(Boolean revoked) {
    this.revoked = revoked;
    return this;
  }

   /**
   * Invite has been revoked
   * @return revoked
  **/
  @ApiModelProperty(value = "Invite has been revoked")
  public Boolean isRevoked() {
    return revoked;
  }

  public void setRevoked(Boolean revoked) {
    this.revoked = revoked;
  }

  public DkPlusAPIModelsMyPageInvite confirmed(Boolean confirmed) {
    this.confirmed = confirmed;
    return this;
  }

   /**
   * Invite has been confirmed
   * @return confirmed
  **/
  @ApiModelProperty(value = "Invite has been confirmed")
  public Boolean isConfirmed() {
    return confirmed;
  }

  public void setConfirmed(Boolean confirmed) {
    this.confirmed = confirmed;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DkPlusAPIModelsMyPageInvite dkPlusAPIModelsMyPageInvite = (DkPlusAPIModelsMyPageInvite) o;
    return Objects.equals(this.id, dkPlusAPIModelsMyPageInvite.id) &&
        Objects.equals(this.email, dkPlusAPIModelsMyPageInvite.email) &&
        Objects.equals(this.company, dkPlusAPIModelsMyPageInvite.company) &&
        Objects.equals(this.expires, dkPlusAPIModelsMyPageInvite.expires) &&
        Objects.equals(this.revoked, dkPlusAPIModelsMyPageInvite.revoked) &&
        Objects.equals(this.confirmed, dkPlusAPIModelsMyPageInvite.confirmed);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, email, company, expires, revoked, confirmed);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DkPlusAPIModelsMyPageInvite {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    company: ").append(toIndentedString(company)).append("\n");
    sb.append("    expires: ").append(toIndentedString(expires)).append("\n");
    sb.append("    revoked: ").append(toIndentedString(revoked)).append("\n");
    sb.append("    confirmed: ").append(toIndentedString(confirmed)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

