/*
 * dkPlus.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.DkCloudDataModelCompanyWebHookSubscription;
import java.util.UUID;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for WebHooksApi
 */
@Ignore
public class WebHooksApiTest {

    private final WebHooksApi api = new WebHooksApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void webHooksDeleteTest() throws ApiException {
        UUID id = null;
        Object response = api.webHooksDelete(id);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void webHooksGetTest() throws ApiException {
        Object response = api.webHooksGet();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void webHooksGetByIdTest() throws ApiException {
        UUID id = null;
        Object response = api.webHooksGetById(id);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void webHooksPostTest() throws ApiException {
        DkCloudDataModelCompanyWebHookSubscription value = null;
        Object response = api.webHooksPost(value);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void webHooksPutTest() throws ApiException {
        UUID id = null;
        DkCloudDataModelCompanyWebHookSubscription value = null;
        Object response = api.webHooksPut(id, value);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void webHooksReceiverTest() throws ApiException {
        Object value = null;
        Object response = api.webHooksReceiver(value);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void webHooksTestTest() throws ApiException {
        DkCloudDataModelCompanyWebHookSubscription value = null;
        Object response = api.webHooksTest(value);

        // TODO: test validations
    }
    
}
